- id: tfsort
  name: tfsort
  description: Run tfsort on all variables.tf and outputs.tf
  entry: hooks/tfsort.sh
  language: script
  files: (variables|outputs)\.tf$
  exclude: \.terraform\/.*$
- id: kms-check
  name: Is KMS key valid
  description: Check if files are encrypted with KMS with the correct key
  entry: hooks/sops-kms-check.sh
  language: script
  files: /secrets\.yaml$
- id: tf-double-newlines
  name: Check for double newlines
  description: Check for double newlines
  entry: hooks/tf-double-newlines.sh
  language: script
  files: .tf$|\.tfvars$|\.hcl$|\.yaml$|\.md$
